export const SQL_CONSTANTS = {
  AND: 'and' as const,
  OR: 'or' as const,
  LIMIT: 'limit' as const,
  SELECT: 'select' as const,
  STAR: '*' as const,
  FROM: 'from' as const,
  WHERE: 'where' as const,
  ORDER_BY: 'order by' as const,
  JOIN: 'join' as const,
  INNER: 'inner' as const,
  LEFT: 'left' as const,
  RIGTH: 'rigth' as const,
  DISTINCT: 'distinct' as const,
  ON: 'on' as const,
  EQUAL: '=' as const,
  WHITE_SPACE: ' ' as const,
  COMMA: ',' as const,
  INSERT_INTO: 'insert into' as const,
  VALUES: 'values' as const,
  RETURNING: 'returning' as const,
  DELETE: 'delete' as const,
  SCHEMA: 'information_schema.columns' as const,
  UPDATE: 'update' as const,
  SET: 'set' as const
}